pull_request_rules:
  - name: backport patches to jdk11 branch
    conditions:
      - base=main
      - label=backport
    actions:
      backport:
        branches:
          - jdk11
        assignees:
          - "{{ author }}"
