name: CI build

on:
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+
  pull_request:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: skjolber/maven-cache-github-action@v1
      with:
        step: restore
    - run: mvn -B -U clean verify
    - uses: skjolber/maven-cache-github-action@v1
      with:
        step: save

  cryostat-test:
    needs: [build]
    strategy:
      matrix:
        arch: [amd64, arm64]
    uses: ./.github/workflows/cryostat-IT.yml
    with:
      build-arch: ${{ matrix.arch }}
      skip-itests: ${{ matrix.arch != 'amd64' }}
