name: CI build

concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

jobs:
  check-before-build:
    runs-on: ubuntu-latest
    steps:
    - name: Fail if safe-to-test is not applied
      if: github.repository_owner == 'cryostatio' && (!contains(github.event.pull_request.labels.*.name, 'safe-to-test'))
      run: exit 1

  build-core:
    runs-on: ubuntu-latest
    outputs:
      core_version: ${{ steps.get_core_version.outputs.core_version }}
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0
    - id: get_core_version
      run: |
        echo "core_version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
        echo "name=$(./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_OUTPUT
    - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        java-version: |
          11
          17
        distribution: 'temurin'
    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ hashFiles('**/pom.xml') }}
    - name: Build cryostat-core
      uses: Wandalen/wretry.action@e68c23e6309f2871ca8ae4763e7629b9c258e1ea # v3.8.0
      with:
        attempt_limit: 3
        command: ./mvnw -B -U clean install

  build-cryostat:
    needs: [build-core]
    runs-on: ubuntu-latest
    env:
        cache-name: cache-yarn
    name: Build Cryostat
    permissions:
        packages: write
        contents: read
        pull-requests: write
        statuses: write
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0
    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        repository: ${{ github.repository_owner }}/cryostat
        ref: ${{ github.base_ref }}
        submodules: true
        fetch-depth: 0
    - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: maven-settings
      uses: s4u/maven-settings-action@894661b3ddae382f1ae8edbeab60987e08cf0788 # v4.0.0
      with:
        servers: '[{"id": "github", "username": "dummy", "password": "${{ secrets.GITHUB_TOKEN }}"}]'
        githubServer: false
    - run: git submodule init && git submodule update
    - name: Cache yarn packages
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: "./src/main/webui/.yarn/cache"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Initialize web assets
      run: |
        cd src/main/webui
        yarn install && yarn yarn:frzinstall
        cd -
    - name: Install podman-docker
      run: |
        sudo apt -y update && sudo apt -y install "podman-docker"
    - name: Start Podman API
      run: systemctl --user enable --now podman.socket
    - name: Set DOCKER_HOST environment variable
      run: echo "DOCKER_HOST=unix:///run/user/$(id -u)/podman/podman.sock" >> "$GITHUB_ENV"
    - name: Build cryostat
      uses: Wandalen/wretry.action@e68c23e6309f2871ca8ae4763e7629b9c258e1ea # v3.8.0
      with:
        attempt_limit: 3
        command: |
          ./mvnw -B \
            -Dio.cryostat.core.version=${{ needs.build-core.outputs.core_version }} \
            -Dquarkus.hibernate-orm.log.sql=false \
            -Dquarkus.log.level=error \
            -Dquarkus.http.access-log.enabled=false \
            -Dquarkus.smallrye-graphql.log-payload=off \
            clean verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Save cryostat image
      run: podman save -o cryostat.tar --format oci-archive quay.io/cryostat/cryostat:latest
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: cryostat
        path: ${{ github.workspace }}/cryostat.tar

  push-to-ghcr:
    runs-on: ubuntu-latest
    needs: [build-cryostat]
    strategy:
      matrix:
        java: ['21']
    outputs:
      amd64_image: ${{ steps.cryostat_amd64_image.outputs.image }}

    permissions:
        packages: write
    steps:
    - name: Download cryostat artifact
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: cryostat
    - name: Load cryostat image
      run: podman load -i cryostat.tar
    - name: Tag cryostat image
      run: podman tag cryostat:latest ghcr.io/${{ github.repository_owner }}/cryostat-core:pr-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}-linux
    - name: Push PR test image to ghcr.io
      id: push-cryostat-to-ghcr
      uses: redhat-actions/push-to-registry@f787883d70a3cc66d399816d0385ac4aec7079f9 # v2.5.1
      with:
        image: cryostat-core
        tags: pr-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}-linux
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.event.pull_request.user.login }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: store cryostat images as output
      id: cryostat_amd64_image
      run: echo "image=${{ steps.push-cryostat-to-ghcr.outputs.registry-path }}" >> "$GITHUB_OUTPUT"

  comment-image:
    runs-on: ubuntu-latest
    needs: [push-to-ghcr]
    env:
      amd64_image: ${{ needs.push-to-ghcr.outputs.amd64_image }}

    permissions:
      pull-requests: write
    steps:
    - name: Create markdown table
      id: md-table
      uses: petems/csv-to-md-table-action@401501a2cdf2512164c1be3b70411976a2b838b9 # v4.0.0
      with:
        csvinput: |
          ARCH, IMAGE
          amd64, ${{ env.amd64_image }}

    - uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
      with:
        message: |-
          ${{ steps.md-table.outputs.markdown-table }}

          To run smoketest:
          ```
          CRYOSTAT_IMAGE=${{ env.amd64_image }} bash smoketest.bash
          ```
