name: CI build

concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

jobs:
  check-before-build:
    runs-on: ubuntu-latest
    steps:
    - name: Fail if safe-to-test is not applied
      if: github.repository_owner == 'cryostatio' && (!contains(github.event.pull_request.labels.*.name, 'safe-to-test'))
      run: exit 1

  spotless:
    needs: [check-before-build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0
    - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Check formatting
      run: ./mvnw -B spotless:check

  spotbugs:
    needs: [check-before-build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0
    - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Run SpotBugs
      run: ./mvnw -B compile spotbugs:check

  compile-and-test:
    needs: [check-before-build]
    runs-on: ubuntu-latest
    outputs:
      core_version: ${{ steps.get_core_version.outputs.core_version }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0
    - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        java-version: |
          11
          17
        distribution: 'temurin'
        cache: 'maven'
    - id: get_core_version
      run: echo "core_version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
    - name: Compile and test cryostat-core
      run: ./mvnw -B clean install -DskipTests=false
    - name: Upload cryostat-core artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: cryostat-core-jars
        path: ~/.m2/repository/io/cryostat/
        if-no-files-found: error

  cryostat-unit-tests:
    needs: [compile-and-test]
    runs-on: ubuntu-latest
    steps:
    - name: Download cryostat-core artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: cryostat-core-jars
        path: ~/.m2/repository/io/cryostat/
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: cryostatio/cryostat
        ref: main
        submodules: true
        fetch-depth: 0
        path: cryostat
    - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'maven'
    - name: maven-settings
      uses: s4u/maven-settings-action@894661b3ddae382f1ae8edbeab60987e08cf0788 # v4.0.0
      with:
        servers: '[{"id": "github", "username": "dummy", "password": "${{ secrets.GITHUB_TOKEN }}"}]'
        githubServer: false
    - name: Run Cryostat surefire unit tests
      run: |
        cd cryostat
        ./mvnw -B \
          -Dio.cryostat.core.version=${{ needs.compile-and-test.outputs.core_version }} \
          -DskipITs=true \
          clean test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cryostat-integration-tests:
    needs: [compile-and-test]
    runs-on: ubuntu-latest
    steps:
    - name: Download cryostat-core artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: cryostat-core-jars
        path: ~/.m2/repository/io/cryostat/
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: cryostatio/cryostat
        ref: main
        submodules: true
        fetch-depth: 0
        path: cryostat
    - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'maven'
    - name: maven-settings
      uses: s4u/maven-settings-action@894661b3ddae382f1ae8edbeab60987e08cf0788 # v4.0.0
      with:
        servers: '[{"id": "github", "username": "dummy", "password": "${{ secrets.GITHUB_TOKEN }}"}]'
        githubServer: false
    - name: Run Cryostat failsafe integration tests
      run: |
        cd cryostat
        ./mvnw -B \
          -Dio.cryostat.core.version=${{ needs.compile-and-test.outputs.core_version }} \
          -Dskip.surefire.tests=true \
          clean verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
