name: CI build and push

on:
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn -B -U clean verify
  publish-snapshot:
    uses: ./.github/workflows/maven-central-release.yml
    secrets: inherit
    if: github.repository_owner == 'cryostatio'
