name: CI build and push

on:
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn -B -U clean verify
  get-version:
    runs-on: ubuntu-latest
    outputs:
      project-version: ${{ steps.get-version.outputs.project-version }}
    steps:
    - id: get-version
      run: |
        PROJECT_VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
        echo "project-version=${PROJECT_VERSION}" >> "${GITHUB_OUTPUT}"
  publish-snapshot:
    needs: get-version
    uses: ./.github/workflows/maven-central-publish.yml
    secrets: inherit
    with:
      publish-cmd: './mvnw -Prelease deploy jreleaser:deploy'
    if: ${{ github.repository_owner == 'cryostatio' && endsWith(needs.get-version.outputs.project-version, '-SNAPSHOT') }}
