# Inspired from https://foojay.io/today/how-to-release-a-java-module-with-jreleaser-to-maven-central-with-github-actions/
name: Publish a new Maven Central release

on:
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: 'Release version'
    #     required: true

jobs:

  publish-release-core:
    uses: ./.github/workflows/maven-central-publish.yml
    secrets: inherit
    with:
      jdk-version: 17
      publish-directory: 'cryostat-core'
      publish-cmd: './release.sh'
    if: ${{ github.repository_owner == 'cryostatio' }}

  publish-release-libcryostat:
    uses: ./.github/workflows/maven-central-publish.yml
    secrets: inherit
    with:
      jdk-version: 11
      publish-directory: 'libcryostat'
      publish-cmd: './release.sh'
    if: ${{ github.repository_owner == 'cryostatio' }}
