# Inspired from https://foojay.io/today/how-to-release-a-java-module-with-jreleaser-to-maven-central-with-github-actions/
name: Publish a new Maven Central release

on:
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: 'Release version'
    #     required: true

jobs:
  publish-release:
    uses: ./.github/workflows/maven-central-publish.yml
    secrets: inherit
    with:
      publish-cmd: './release.sh'
    if: ${{ github.repository_owner == 'cryostatio' }}
