name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}
    - uses: skjolber/maven-cache-github-action@v1
      with:
        step: restore
    - name: Publish package
      run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
    - uses: skjolber/maven-cache-github-action@v1
      with:
        step: save
